### ISSUE TITLE
Hacer scripts paramétricos

### ISSUE THREAD

**Issue by AlmuHS** [RafaelAybar/Bash-toolkit#1]
Mirando los scripts, veo que los datos los obtiene de teclado, desde preguntas o menús incluidos en los propios script.

Sería buena idea sacar esas peticiones de teclado a otros scripts, y hacer que aquellos script que realizan las operaciones, reciban los datos desde parámetros.

Así. un administrador de sistemas, podría usar esos script para automatizar ciertas tareas, simplemente indicando por parámetro los datos que el necesita.

**Comment by RafaelAybar** [comment]
Lo implementaré en el script de redes, y luego veré si lo implemento en el resto de los scripts. ¡Muchas gracias por la sugerencia!

**Comment by RafaelAybar** [comment]
Actualización: el script de red ahora es paramétrico

**Comment by AlmuHS** [comment]
No has entendido la idea.
Hacer un script paramétrico quiere decir que NO RECIBA NINGUNA INFORMACIÓN DESDE TECLADO. Lo que te explicaba de la automatización de tareas era solo un ejemplo de como se podría utilizar un script así.

La idea es sacar todas las peticiones de datos desde teclado FUERA DEL SCRIPT, a otro script interfaz, o simplemente quitarlas.

De esta forma, el script solo quedaría con los parámetros introducidos desde linea de comandos ($1, $2, ... etc), y con esos sería con los que realizaría las operaciones de configuración, instalación, etc

**Comment by RafaelAybar** [comment]
Mira la rama de pruebas, es ahí donde he hecho los cambios

**Comment by AlmuHS** [comment]
Vale, estaba mirando la rama equivocada. Ya lo he visto
